services:
  - type: web
    name: procurebot-backend
    env: node
    buildCommand: npm install && npx playwright install --with-deps chromium
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD
        value: "0"
